# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'reg.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginForm(object):
    def setupUi(self, LoginForm):
        LoginForm.setObjectName("LoginForm")
        LoginForm.resize(433, 253)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(LoginForm.sizePolicy().hasHeightForWidth())
        LoginForm.setSizePolicy(sizePolicy)
        LoginForm.setMinimumSize(QtCore.QSize(433, 253))
        LoginForm.setMaximumSize(QtCore.QSize(433, 253))
        self.centralwidget = QtWidgets.QWidget(LoginForm)
        self.centralwidget.setObjectName("centralwidget")
        self.login = QtWidgets.QPushButton(self.centralwidget)
        self.login.setGeometry(QtCore.QRect(170, 150, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.login.setFont(font)
        self.login.setObjectName("login")
        self.registration = QtWidgets.QPushButton(self.centralwidget)
        self.registration.setGeometry(QtCore.QRect(160, 190, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.registration.setFont(font)
        self.registration.setObjectName("registration")
        self.loginEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.loginEdit.setGeometry(QtCore.QRect(110, 80, 211, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setUnderline(False)
        self.loginEdit.setFont(font)
        self.loginEdit.setAutoFillBackground(False)
        self.loginEdit.setStyleSheet("")
        self.loginEdit.setInputMask("")
        self.loginEdit.setText("")
        self.loginEdit.setClearButtonEnabled(True)
        self.loginEdit.setObjectName("loginEdit")
        self.passwordEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.passwordEdit.setGeometry(QtCore.QRect(110, 120, 211, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.passwordEdit.setFont(font)
        self.passwordEdit.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.passwordEdit.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhNoAutoUppercase|QtCore.Qt.ImhNoPredictiveText|QtCore.Qt.ImhSensitiveData)
        self.passwordEdit.setInputMask("")
        self.passwordEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordEdit.setClearButtonEnabled(True)
        self.passwordEdit.setObjectName("passwordEdit")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(60, 30, 311, 31))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        LoginForm.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(LoginForm)
        self.statusbar.setObjectName("statusbar")
        LoginForm.setStatusBar(self.statusbar)

        self.retranslateUi(LoginForm)
        QtCore.QMetaObject.connectSlotsByName(LoginForm)

    def retranslateUi(self, LoginForm):
        _translate = QtCore.QCoreApplication.translate
        LoginForm.setWindowTitle(_translate("LoginForm", "Польская запись"))
        self.login.setText(_translate("LoginForm", "Вход"))
        self.registration.setText(_translate("LoginForm", "Регистрация"))
        self.loginEdit.setPlaceholderText(_translate("LoginForm", "Логин"))
        self.passwordEdit.setPlaceholderText(_translate("LoginForm", "Пароль"))
        self.label.setText(_translate("LoginForm", "Для использования калькулятора надо зарегистрироваться"))
